[package]
name = "yellow"
version = "0.1.0"
authors = ["Druue <tileyratkins@gmail.com>", "Halvard Mørstad <halvard@simplyundoable.com> (https://twitter.com/halvardssm)"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
