name: Yellow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Check Formatting
      run: cargo fmt -- --check
    - name: Build the Docker image
      run: make setup
    - name: Run tests
      run: make test
