name: Yellow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      uses: whoan/docker-build-with-cache-action@v5.0.1
      with:
        image_name: yellow
        dockerfile: ./Dockerfile
    - name: Check Formatting
      run: cargo fmt -- --check
    - name: Run tests
      run: make test
